import {
    Bot, Mic, Sparkles, MessageCircle, Code, Image, Video, GraduationCap,
    Palette, PenTool, Music, Globe, BookOpenCheck, Users, Search, Languages,
    Brain, Gamepad, Megaphone, BadgeHelp, Settings, LayoutTemplate, FileText, Podcast
  } from "lucide-react";
  
  export const iconMap: Record<string, any> = {
    "Audio": Mic,
    "Automatización": Sparkles,
    "Chat": MessageCircle,
    "Codificación": Code,
    "Detección": Bot,
    "Diseño gráfico": Palette,
    "Edición de imágenes": Image,
    "Edición de vídeo": Video,
    "Educación": GraduationCap,
    "Generación de arte": PenTool,
    "Generación de texto": FileText,
    "Generación de vídeo": Video,
    "Generación de diseño": LayoutTemplate,
    "Gestión": Settings,
    "Juegos": Gamepad,
    "Marketing": Megaphone,
    "Publicidad": Megaphone,
    "Marketing de contenidos": BookOpenCheck,
    "Música": Music,
    "Plataformas sin código": LayoutTemplate,
    "Podcasting": Podcast,
    "Productividad": Sparkles,
    "Redacción": FileText,
    "Reclutamiento": Users,
    "Redes sociales": MessageCircle,
    "SEO": Search,
    "Texto a vídeo": Video,
    "Texto a voz": Mic,
    "Traducción": Languages,
    "Inteligencia de negocios": Brain,
    "Citas": BadgeHelp,
  };
  
  export const descriptionMap: Record<string, string> = {
    "Audio": "Convierte o genera audio mediante IA.",
    "Automatización": "Optimiza tareas repetitivas.",
    "Chat": "Interfaces de conversación automatizadas.",
    "Codificación": "Asistentes para desarrollo y debugging.",
    "Detección": "Identifica patrones, fraudes o contenido.",
    "Diseño gráfico": "Herramientas visuales impulsadas por IA.",
    "Edición de imágenes": "Transforma o mejora imágenes automáticamente.",
    "Edición de vídeo": "Edita videos con inteligencia artificial.",
    "Educación": "Plataformas y recursos para aprender con IA.",
    "Generación de arte": "Crea ilustraciones a partir de texto o estilo.",
    "Generación de texto": "Escribe contenido automáticamente.",
    "Generación de vídeo": "Crea videos a partir de ideas o texto.",
    "Generación de diseño": "Diseños estructurales generados automáticamente.",
    "Gestión": "Soluciones para organizar y administrar proyectos.",
    "Juegos": "Creación o asistencia en videojuegos.",
    "Marketing": "Mejora y automatiza campañas publicitarias.",
    "Publicidad": "Herramientas para anuncios con IA.",
    "Marketing de contenidos": "Estrategias de contenido automatizadas.",
    "Música": "Generación o edición de música asistida.",
    "Plataformas sin código": "Crea sin necesidad de programar.",
    "Podcasting": "Edita o lanza podcasts con IA.",
    "Productividad": "Haz más con menos esfuerzo.",
    "Redacción": "Generadores y editores de texto.",
    "Reclutamiento": "IA para contratar mejor y más rápido.",
    "Redes sociales": "Optimiza tu contenido en plataformas sociales.",
    "SEO": "Mejora el posicionamiento de tu sitio.",
    "Texto a vídeo": "Transforma ideas escritas en video.",
    "Texto a voz": "Convierte texto en locución natural.",
    "Traducción": "Traduce idiomas automáticamente.",
    "Inteligencia de negocios": "Toma mejores decisiones con datos.",
    "Citas": "Apps para conectar personas con IA.",
  };
  